baseURL = 'https://neceser.co/'
languageCode = 'es'
title = 'nece ser'
theme = 'PaperMod'

[params]
  author = "nece ser"
  description = "Cocinando"
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true